export const buildingCodeToName = {
  "3SC": "300 S. Craig (Police)",
  "4SC": "407 S. Craig",
  // AH: "Alumni House",
  AN: "Ansys Hall",
  BH: "Baker Hall",
  // BR: "Bramer House",
  CC: "417 S. Craig",
  CFA: "College of Fine Arts",
  CUC: "Cohon University Center",
  CYH: "Cyert Hall",
  DH: "Doherty Hall",
  EDS: "Smith Hall",
  // FRB: "4615 Forbes (CTTEC)",
  FM: "Facilities Management Services Building",
  GHC: "Gates & Hillman Centers",
  HBH: "Hamburg Hall",
  HH: "Hamerschlag Hall",
  HL: "Hunt Library",
  HOA: "Hall of the Arts",
  // INI: "4616 Henry",
  // MC: "4721 Fifth Ave (CDFD)",
  MI: "Mellon Institute",
  MM: "Margaret Morrison Carnegie Hall",
  NSH: "Newell-Simon Hall",
  PC: "Posner Center",
  PCA: "Purnell Center for the Arts",
  PH: "Porter Hall",
  POS: "Posner Hall",
  SC: "Scott Hall",
  SH: "Scaife Hall",
  TCS: "TCS Hall",
  TEP: "Tepper Building",
  // UT: "4516 Henry (UTDC)",
  WEH: "Wean Hall",
  // WF: "Whitfield Hall",
  // WH: "Warner Hall",
  WWG: "West Wing",
  // WQ: "WQED Building",
  // outside: "Campus Outside",

  MGE: "E-Tower",
  RES: "Resnik House",
  FBA: "Forbes Beeler Apartments",
  MOR: "Morewood Gardens",

  REH: "Roberts Engineering Hall",
};

export const connectedBuildings = {
  POS: ["HOA", "PC"],
  HOA: ["POS"],
  BH: ["PH"],
  PH: ["BH", "AN"],
  AN: ["PH"],
  WEH: ["DH", "SC", "NSH"],
  DH: ["WEH"],
  PC: ["POS"],
  NSH: ["GHC", "WEH"],
  GHC: ["NSH"],
  SC: ["HH", "WEH"],
};
